#
# CaramOS — pacman.conf for ISO building
#
[options]
HoldPkg     = pacman glibc
Architecture = auto
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# CaramOS custom repository
[caramos]
SigLevel = Optional TrustAll
Server = https://github.com/minhmc2007/CaramOS-Repo/releases/download/repo-latest

# Official repositories
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
